// One meeting: summary, transcript, notes, and speakers, with Reveal in
// Finder and Retry where processing failed. The summary is the user's
// document once produced: editable in place, saved on its own, and only
// regenerated by an explicit Retry. Chat lives in an input along the bottom
// that opens a conversation drawer, Granola-style.

import AppKit
import MeetingNotesCore
import SwiftUI
import UniformTypeIdentifiers

struct MeetingDetailScreen: View {
    @EnvironmentObject var model: AppModel
    let meetingID: String

    @State private var detail: MeetingDetail?
    @State private var tab = "Summary"
    @State private var notesDraft = ""
    @State private var lastSavedNotes = ""
    @FocusState private var notesFocused: Bool
    @State private var summaryDraft = ""
    @State private var lastSavedSummary = ""
    @FocusState private var summaryFocused: Bool
    @State private var titleDraft: String?
    @FocusState private var titleFocused: Bool
    @State private var chatHistory: [(question: String, answer: String)] = []
    @State private var chatQuestion = ""
    @State private var chatBusy = false
    @State private var chatDrawerOpen = false
    @State private var editingSummary = false
    @AppStorage(Appearance.sizeKey) private var baseFontSize = Appearance.defaultSize
    @AppStorage(Appearance.designKey) private var fontDesign = "system"
    @State private var pasteMonitor: Any?
    @State private var showRegeneratePrompt = false
    @State private var keepEditsChosen = false
    @State private var showDeleteConfirm = false
    @State private var showFindReplace = false
    @State private var recordedDate = Date()
    @State private var loadedDate: Date?

    private var contentFont: Font {
        Appearance.font(size: baseFontSize, design: fontDesign)
    }

    var body: some View {
        VStack(spacing: 0) {
            if let detail {
                header(detail)
                Picker("", selection: $tab) {
                    ForEach(["Summary", "Transcript", "Notes", "Speakers"], id: \.self) { Text($0) }
                }
                .pickerStyle(.segmented)
                .padding(.horizontal)
                content(detail)
                if !chatDrawerOpen {
                    Divider()
                    chatInputBar
                }
            } else {
                ProgressView().frame(maxWidth: .infinity, maxHeight: .infinity)
            }
        }
        .overlay {
            if chatDrawerOpen {
                GeometryReader { geometry in
                    VStack(spacing: 0) {
                        Spacer()
                        ChatDrawer(
                            history: chatHistory,
                            question: $chatQuestion,
                            busy: chatBusy,
                            onAsk: ask,
                            onClose: { chatDrawerOpen = false })
                        .frame(height: geometry.size.height / 2)
                    }
                }
                .transition(.move(edge: .bottom))
            }
        }
        .animation(.easeInOut(duration: 0.2), value: chatDrawerOpen)
        .alert("Regenerate the summary?", isPresented: $showRegeneratePrompt) {
            Button("Regenerate") {
                Task {
                    try? await model.client.regenerateSummary(meetingID)
                    await reload(keepingDraft: true)
                }
            }
            Button("Keep my edits", role: .cancel) { keepEditsChosen = true }
        } message: {
            Text("You have edited this summary by hand. Regenerating replaces "
                 + "your edits with a fresh summary written from the transcript "
                 + "and the current notes.")
        }
        .alert("Delete this meeting?", isPresented: $showDeleteConfirm) {
            Button("Delete", role: .destructive) {
                Task {
                    try? await model.client.deleteMeeting(meetingID)
                    model.selectedMeetingID = nil
                    await model.refreshLibrary()
                }
            }
            Button("Cancel", role: .cancel) {}
        } message: {
            Text("The recording, transcript, summary, and notes are removed "
                 + "from the vault. Voices you have named stay remembered.")
        }
        .sheet(isPresented: $showFindReplace) {
            FindReplaceSheet(summary: summaryDraft, notes: notesDraft, replace: performReplace)
        }
        .task(id: meetingID) {
            chatHistory = []
            chatDrawerOpen = false
            keepEditsChosen = false
            await reload()
            // Keep the open meeting fresh while it is still being processed, so
            // a stage change or failure shows without a click. Once it has
            // settled there is nothing to poll for, and stopping lets the summary
            // stay still enough to select and copy.
            while !Task.isCancelled, !isSettled {
                try? await Task.sleep(for: .seconds(2))
                await reload(keepingDraft: true)
            }
        }
    }

    /// True when the meeting has finished processing (or failed) and its summary
    /// is no longer pending, so there is no further live update to wait for.
    private var isSettled: Bool {
        guard let detail else { return false }
        if detail.processing_status == "failed" { return true }
        return detail.processing_status == "ready" && detail.summary_status != "pending"
    }

    // MARK: - Header

    @ViewBuilder
    private func header(_ detail: MeetingDetail) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            HStack {
                if titleDraft != nil {
                    TextField("Meeting title", text: Binding(
                        get: { titleDraft ?? "" },
                        set: { titleDraft = $0 }))
                        .textFieldStyle(.roundedBorder)
                        .font(.title2)
                        .frame(maxWidth: 420)
                        .focused($titleFocused)
                        .onAppear { titleFocused = true }
                        .onSubmit { saveTitle() }
                        .onExitCommand { titleDraft = nil }
                        .onChange(of: titleFocused) { _, focused in
                            if !focused && titleDraft != nil { saveTitle() }
                        }
                } else {
                    Text(detail.title)
                        .font(.title2).bold()
                        .onTapGesture { titleDraft = detail.title }
                        .help("Click to rename this meeting")
                }
                Spacer()
                if detail.processing_status == "failed" {
                    Button("Retry from \(detail.failed_stage ?? "the failed stage")") {
                        Task {
                            try? await model.client.retry(meetingID)
                            await reload()
                            await model.refreshLibrary()
                        }
                    }
                }
                Menu {
                    Button("Reveal in Finder") {
                        model.revealInFinder(path: detail.reveal_path)
                    }
                    Button("Regenerate summary") {
                        if detail.summary_edited == 1 {
                            showRegeneratePrompt = true
                        } else {
                            Task {
                                try? await model.client.regenerateSummary(meetingID)
                                await reload(keepingDraft: true)
                            }
                        }
                    }
                    .disabled(detail.transcript == nil)
                    Button("Find and replace…") { showFindReplace = true }
                    Divider()
                    Button("Delete meeting", role: .destructive) {
                        showDeleteConfirm = true
                    }
                } label: {
                    Image(systemName: "ellipsis")
                        .font(.system(size: 14, weight: .semibold))
                        .foregroundStyle(.primary)
                        .frame(width: 32, height: 26)
                        .background(Color.secondary.opacity(0.15))
                        .clipShape(RoundedRectangle(cornerRadius: 7))
                }
                .menuStyle(.borderlessButton)
                .menuIndicator(.hidden)
                .fixedSize()
                .help("More actions: reveal in Finder, regenerate summary, delete")
            }
            if detail.processing_status == "failed" {
                Text(detail.last_error ?? "Processing failed.")
                    .font(.caption)
                    .foregroundStyle(.red)
                    .frame(maxWidth: .infinity, alignment: .trailing)
            }
            HStack(spacing: 6) {
                Image(systemName: "calendar")
                    .font(.caption).foregroundStyle(.secondary)
                DatePicker(
                    "Recorded", selection: $recordedDate,
                    displayedComponents: [.date, .hourAndMinute])
                    .datePickerStyle(.compact)
                    .labelsHidden()
                    .controlSize(.small)
                    .fixedSize()
                    .help("Adjust the recorded date, e.g. for an import filed on the wrong day")
                    .onChange(of: recordedDate) { _, newValue in
                        // The date is also set from the loaded meeting; only a real
                        // user change (more than a second off the loaded value)
                        // saves, so setting it on load does not loop.
                        guard let loaded = loadedDate,
                              abs(newValue.timeIntervalSince(loaded)) > 1 else { return }
                        loadedDate = newValue
                        saveRecordedDate(newValue)
                    }
            }
            FolderBar(meetingID: meetingID, currentFolder: detail.folder) {
                await reload(keepingDraft: true)
                await model.refreshLibrary()
            }
        }
        .padding()
    }

    // MARK: - Tabs

    @ViewBuilder
    private func content(_ detail: MeetingDetail) -> some View {
        switch tab {
        case "Transcript":
            if let transcript = detail.transcript {
                ScrollView { RichMarkdownView(text: transcript, lazy: true).padding() }
            } else {
                MarkdownPane(text: "No transcript yet. It appears when processing reaches that stage.")
            }
        case "Notes":
            VStack(alignment: .leading) {
                TextEditor(text: $notesDraft)
                    .font(contentFont)
                    .focused($notesFocused)
                    .onChange(of: notesFocused) { _, focused in
                        if !focused { saveNotes() }
                    }
                let images = pastedImageURLs(in: notesDraft, revealPath: detail.reveal_path)
                if !images.isEmpty {
                    ScrollView(.horizontal, showsIndicators: false) {
                        HStack(spacing: 8) {
                            ForEach(images, id: \.self) { url in
                                if let image = NSImage(contentsOf: url) {
                                    Image(nsImage: image)
                                        .resizable()
                                        .scaledToFit()
                                        .frame(height: 90)
                                        .clipShape(RoundedRectangle(cornerRadius: 6))
                                        .overlay(RoundedRectangle(cornerRadius: 6)
                                            .stroke(.secondary.opacity(0.3)))
                                }
                            }
                        }
                    }
                    .frame(height: 96)
                }
                HStack {
                    Text("Notes save on their own and feed into the summary; they are "
                         + "never rewritten. Paste screenshots straight in; they are "
                         + "stored with the meeting.")
                        .font(.caption).foregroundStyle(.secondary)
                    Spacer()
                    Button("Paste image") { pasteImageFromPasteboard() }
                        .disabled(!Self.pasteboardHasImage())
                }
            }
            .padding()
            .onAppear { installPasteMonitor() }
            .onDisappear {
                removePasteMonitor()
                saveNotes()
            }
        case "Speakers":
            SpeakersTab(meetingID: meetingID, attendees: detail.attendees.map(\.name)) {
                await reload(keepingDraft: true)
            }
        default:
            summaryTab(detail)
        }
    }

    @ViewBuilder
    private func summaryTab(_ detail: MeetingDetail) -> some View {
        if detail.summary == nil {
            MarkdownPane(text: detail.summary_status == "pending"
                ? "The summary is pending. It is written when LM Studio is reachable with a model loaded."
                : "No summary yet.")
        } else if editingSummary {
            VStack(alignment: .leading) {
                HStack {
                    Text("Editing summary").font(.caption).foregroundStyle(.secondary)
                    Spacer()
                    Button("Done") {
                        saveSummary()
                        editingSummary = false
                    }
                }
                TextEditor(text: $summaryDraft)
                    .font(contentFont)
                    .focused($summaryFocused)
            }
            .padding()
            .onDisappear {
                saveSummary()
                editingSummary = false
            }
        } else {
            VStack(alignment: .leading, spacing: 8) {
                HStack {
                    Spacer()
                    Button {
                        summaryFocused = true
                        editingSummary = true
                    } label: {
                        Label("Edit", systemImage: "pencil")
                    }
                    .buttonStyle(.borderless)
                }
                ScrollView { RichMarkdownView(text: summaryDraft).padding(.bottom) }
            }
            .padding()
        }
    }

    // MARK: - Chat

    private var chatInputBar: some View {
        HStack {
            TextField("Ask about this meeting…", text: $chatQuestion)
                .softField()
                .onSubmit { ask() }
            if chatBusy { ProgressView().controlSize(.small) }
            if !chatHistory.isEmpty && !chatDrawerOpen {
                Button("Show conversation") { chatDrawerOpen = true }
            }
        }
        .padding(10)
    }

    private func ask() {
        let question = chatQuestion.trimmingCharacters(in: .whitespaces)
        guard !question.isEmpty, !chatBusy else { return }
        chatQuestion = ""
        chatDrawerOpen = true
        chatBusy = true
        Task {
            defer { chatBusy = false }
            do {
                let answer = try await model.client.chat(
                    meetingID, question: question, history: chatHistory)
                chatHistory.append((question, answer))
            } catch {
                chatHistory.append((question, "The model could not answer: \(error.localizedDescription)"))
            }
        }
    }

    // MARK: - Saving

    private func saveTitle() {
        let title = (titleDraft ?? "").trimmingCharacters(in: .whitespaces)
        titleDraft = nil
        guard !title.isEmpty, title != detail?.title else { return }
        Task {
            try? await model.client.renameMeeting(meetingID, title: title)
            await reload(keepingDraft: true)
            await model.refreshLibrary()
        }
    }

    private func saveNotes() {
        let text = notesDraft
        guard text != lastSavedNotes else { return }
        lastSavedNotes = text
        Task {
            if let action = try? await model.client.saveNotes(meetingID, text: text) {
                handleSummaryAction(action)
            }
        }
    }

    private func handleSummaryAction(_ action: String) {
        // "regenerating" needs nothing: the poll shows the stage. "prompt"
        // asks once; choosing to keep the edits stays chosen for this meeting.
        if action == "prompt" && !keepEditsChosen {
            showRegeneratePrompt = true
        }
    }

    /// Replace a term across this meeting's summary and notes, saving each
    /// through the normal edit path (so an edited summary is not regenerated
    /// over). Returns how many replacements were made in each.
    private func performReplace(_ find: String, _ replacement: String, _ caseSensitive: Bool)
        -> (summary: Int, notes: Int) {
        let inSummary = TextReplace.replacingAll(
            in: summaryDraft, find: find, with: replacement, caseSensitive: caseSensitive)
        let inNotes = TextReplace.replacingAll(
            in: notesDraft, find: find, with: replacement, caseSensitive: caseSensitive)
        if inSummary.count > 0 {
            summaryDraft = inSummary.text
            saveSummary()
        }
        if inNotes.count > 0 {
            notesDraft = inNotes.text
            saveNotes()
        }
        return (inSummary.count, inNotes.count)
    }

    /// Parses the stored started_at (which carries the local offset).
    private static let isoParser: ISO8601DateFormatter = {
        let f = ISO8601DateFormatter()
        f.formatOptions = [.withInternetDateTime]
        return f
    }()

    /// Formats a picked date as local wall-clock time with no offset; the
    /// backend attaches the machine's local offset, so what the user sees is
    /// what is stored.
    private static let localWallClock: DateFormatter = {
        let f = DateFormatter()
        f.locale = Locale(identifier: "en_US_POSIX")
        f.dateFormat = "yyyy-MM-dd'T'HH:mm:ss"
        return f
    }()

    private func saveRecordedDate(_ date: Date) {
        let value = Self.localWallClock.string(from: date)
        Task {
            try? await model.client.setMeetingDate(meetingID, startedAt: value)
            await reload(keepingDraft: true)
            await model.refreshLibrary()  // re-files it under the new day
        }
    }

    private func saveSummary() {
        let text = summaryDraft
        guard detail?.summary != nil, text != lastSavedSummary, !text.isEmpty else { return }
        lastSavedSummary = text
        Task {
            try? await model.client.saveSummary(meetingID, body: text)
            // Refresh so the menu's Regenerate sees the summary is now edited
            // and asks before replacing it.
            await reload(keepingDraft: true)
        }
    }

    private func reload(keepingDraft: Bool = false) async {
        guard let fresh = try? await model.client.meeting(meetingID) else { return }
        // Only publish a genuine change. The open meeting is polled every couple
        // of seconds; reassigning an identical detail would re-render the summary
        // and clear any text the user is selecting mid-drag.
        if detail != fresh { detail = fresh }
        // Adopt the recorded date on first load and whenever the server's value
        // changes (e.g. after a save), but not on every poll, so it never
        // clobbers a date the user is mid-adjustment on.
        if let parsed = Self.isoParser.date(from: fresh.started_at), parsed != loadedDate {
            loadedDate = parsed
            recordedDate = parsed
        }
        if !keepingDraft || notesDraft.isEmpty {
            notesDraft = fresh.notes
            lastSavedNotes = fresh.notes
        }
        let freshSummary = summaryBody(fresh)
        if !keepingDraft || summaryDraft.isEmpty || summaryDraft == lastSavedSummary {
            // Adopt outside changes (a rename patch, a regeneration) unless
            // the user has unsaved edits in the editor right now.
            if freshSummary != lastSavedSummary {
                summaryDraft = freshSummary
                lastSavedSummary = freshSummary
            } else if !keepingDraft {
                summaryDraft = freshSummary
            }
        }
    }

    private func summaryBody(_ detail: MeetingDetail) -> String {
        guard let summary = detail.summary else { return "" }
        // meeting.md carries front matter; the editor holds only the body.
        if summary.hasPrefix("---\n"),
           let range = summary.range(of: "\n---\n", range: summary.index(summary.startIndex, offsetBy: 4)..<summary.endIndex) {
            return String(summary[range.upperBound...]).trimmingCharacters(in: .whitespacesAndNewlines)
        }
        return summary
    }

    /// The image files linked from the notes body, resolved against the
    /// meeting folder on disk so the thumbnails render locally.
    private func pastedImageURLs(in notes: String, revealPath: String) -> [URL] {
        let base = URL(fileURLWithPath: revealPath)
        let pattern = #"!\[[^\]]*\]\((assets/[^)]+)\)"#
        guard let regex = try? NSRegularExpression(pattern: pattern) else { return [] }
        let range = NSRange(notes.startIndex..., in: notes)
        return regex.matches(in: notes, range: range).compactMap { match in
            guard let r = Range(match.range(at: 1), in: notes) else { return nil }
            let url = base.appendingPathComponent(String(notes[r]))
            return FileManager.default.fileExists(atPath: url.path) ? url : nil
        }
    }

    static func pasteboardHasImage() -> Bool {
        NSPasteboard.general.canReadItem(withDataConformingToTypes: [
            UTType.png.identifier, UTType.tiff.identifier,
        ])
    }

    /// The text view underneath TextEditor consumes paste itself and drops
    /// image data on the floor, so onPasteCommand never fires. While the
    /// notes tab is open, a local key monitor routes an image-carrying paste
    /// here; plain text pasting stays native.
    private func installPasteMonitor() {
        guard pasteMonitor == nil else { return }
        pasteMonitor = NSEvent.addLocalMonitorForEvents(matching: .keyDown) { event in
            guard event.modifierFlags.contains(.command),
                  event.charactersIgnoringModifiers?.lowercased() == "v",
                  Self.pasteboardHasImage()
            else { return event }
            pasteImageFromPasteboard()
            return nil
        }
    }

    private func removePasteMonitor() {
        if let pasteMonitor {
            NSEvent.removeMonitor(pasteMonitor)
        }
        pasteMonitor = nil
    }

    private func pasteImageFromPasteboard() {
        let pasteboard = NSPasteboard.general
        let png = pasteboard.data(forType: .png)
            ?? pasteboard.data(forType: .tiff).flatMap {
                NSBitmapImageRep(data: $0)?.representation(using: .png, properties: [:])
            }
        guard let png else { return }
        Task {
            // Typed text first, so the backend appends the image link after it.
            lastSavedNotes = notesDraft
            _ = try? await model.client.saveNotes(meetingID, text: notesDraft)
            _ = try? await model.client.pasteImage(meetingID, data: png)
            if let fresh = try? await model.client.meeting(meetingID) {
                detail = fresh
                notesDraft = fresh.notes
                lastSavedNotes = fresh.notes
            }
            // No regenerate prompt mid-paste: the image is added at once, and
            // an edited summary is left for the menu's Regenerate to offer.
            // A machine summary was already re-queued by the backend.
        }
    }
}

// MARK: - The conversation drawer

struct ChatDrawer: View {
    let history: [(question: String, answer: String)]
    @Binding var question: String
    let busy: Bool
    let onAsk: () -> Void
    let onClose: () -> Void

    var body: some View {
        VStack(spacing: 0) {
            HStack {
                Text("Conversation").font(.headline)
                Spacer()
                Button {
                    onClose()
                } label: {
                    Image(systemName: "chevron.down")
                }
                .buttonStyle(.borderless)
                .help("Close the conversation")
            }
            .padding(12)
            Divider()
            ScrollViewReader { proxy in
                ScrollView {
                    VStack(alignment: .leading, spacing: 14) {
                        ForEach(history.indices, id: \.self) { index in
                            VStack(alignment: .leading, spacing: 4) {
                                Text(history[index].question).bold()
                                Text(LocalizedStringKey(history[index].answer))
                                    .textSelection(.enabled)
                            }
                            .id(index)
                        }
                        if busy { ProgressView().controlSize(.small) }
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding(12)
                }
                .onChange(of: history.count) { _, count in
                    withAnimation { proxy.scrollTo(max(0, count - 1), anchor: .bottom) }
                }
            }
            Divider()
            HStack {
                TextField("Follow up…", text: $question)
                    .softField()
                    .onSubmit { onAsk() }
                if busy { ProgressView().controlSize(.small) }
            }
            .padding(10)
        }
        .background(.regularMaterial)
        .clipShape(UnevenRoundedRectangle(topLeadingRadius: 10, topTrailingRadius: 10))
        .shadow(radius: 8)
    }
}

struct MarkdownPane: View {
    let text: String

    var body: some View {
        ScrollView {
            Text(LocalizedStringKey(text))
                .frame(maxWidth: .infinity, alignment: .leading)
                .textSelection(.enabled)
                .padding()
        }
    }
}

/// Find and replace a name or term across one meeting's summary and notes, with
/// a live match count before committing. The replace closure applies and saves.
struct FindReplaceSheet: View {
    let summary: String
    let notes: String
    let replace: (String, String, Bool) -> (summary: Int, notes: Int)

    @Environment(\.dismiss) private var dismiss
    @State private var find = ""
    @State private var replacement = ""
    @State private var caseSensitive = false
    @State private var result: String?

    private var matches: (summary: Int, notes: Int) {
        guard !find.isEmpty else { return (0, 0) }
        return (TextReplace.count(in: summary, find: find, caseSensitive: caseSensitive),
                TextReplace.count(in: notes, find: find, caseSensitive: caseSensitive))
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 14) {
            Text("Find and replace").font(.headline)
            Text("Correct a mis-heard name or term everywhere in this meeting's "
                 + "summary and notes at once.")
                .font(.caption).foregroundStyle(.secondary)

            TextField("Find", text: $find)
                .textFieldStyle(.roundedBorder)
            TextField("Replace with", text: $replacement)
                .textFieldStyle(.roundedBorder)
            Toggle("Match case", isOn: $caseSensitive)

            if !find.isEmpty {
                let total = matches.summary + matches.notes
                Text(total == 0
                     ? "No matches."
                     : "\(phrase(total, "match", "matches")): "
                        + "\(matches.summary) in the summary, \(matches.notes) in the notes.")
                    .font(.caption).foregroundStyle(.secondary)
            }
            if let result {
                Label(result, systemImage: "checkmark.circle.fill")
                    .font(.caption).foregroundStyle(.green)
            }

            HStack {
                Spacer()
                Button("Done") { dismiss() }
                Button("Replace all") {
                    let done = replace(find, replacement, caseSensitive)
                    let total = done.summary + done.notes
                    result = "Replaced \(phrase(total, "occurrence", "occurrences")): "
                        + "\(done.summary) in the summary, \(done.notes) in the notes."
                }
                .keyboardShortcut(.defaultAction)
                .disabled(find.isEmpty || (matches.summary + matches.notes) == 0)
            }
        }
        .padding(20)
        .frame(width: 440)
    }

    private func phrase(_ n: Int, _ singular: String, _ plural: String) -> String {
        "\(n) \(n == 1 ? singular : plural)"
    }
}
