// One meeting: summary, transcript, notes, and speakers, with Reveal in
// Finder and Retry where processing failed. The summary is the user's
// document once produced: editable in place, saved on its own, and only
// regenerated by an explicit Retry. Chat lives in an input along the bottom
// that opens a conversation drawer, Granola-style.

import AppKit
import MeetingNotesCore
import SwiftUI
import UniformTypeIdentifiers

struct MeetingDetailScreen: View {
    @EnvironmentObject var model: AppModel
    let meetingID: String

    @State private var detail: MeetingDetail?
    @State private var tab = "Summary"
    @State private var notesDraft = ""
    @State private var lastSavedNotes = ""
    @FocusState private var notesFocused: Bool
    @State private var summaryDraft = ""
    @State private var lastSavedSummary = ""
    @FocusState private var summaryFocused: Bool
    @State private var titleDraft: String?
    @FocusState private var titleFocused: Bool
    @State private var chatHistory: [(question: String, answer: String)] = []
    @State private var chatQuestion = ""
    @State private var chatBusy = false
    @State private var chatDrawerOpen = false
    @AppStorage(Appearance.sizeKey) private var baseFontSize = Appearance.defaultSize
    @AppStorage(Appearance.designKey) private var fontDesign = "system"

    private var contentFont: Font {
        Appearance.font(size: baseFontSize, design: fontDesign)
    }

    var body: some View {
        VStack(spacing: 0) {
            if let detail {
                header(detail)
                Picker("", selection: $tab) {
                    ForEach(["Summary", "Transcript", "Notes", "Speakers"], id: \.self) { Text($0) }
                }
                .pickerStyle(.segmented)
                .padding(.horizontal)
                content(detail)
                if !chatDrawerOpen {
                    Divider()
                    chatInputBar
                }
            } else {
                ProgressView().frame(maxWidth: .infinity, maxHeight: .infinity)
            }
        }
        .overlay {
            if chatDrawerOpen {
                GeometryReader { geometry in
                    VStack(spacing: 0) {
                        Spacer()
                        ChatDrawer(
                            history: chatHistory,
                            question: $chatQuestion,
                            busy: chatBusy,
                            onAsk: ask,
                            onClose: { chatDrawerOpen = false })
                        .frame(height: geometry.size.height / 2)
                    }
                }
                .transition(.move(edge: .bottom))
            }
        }
        .animation(.easeInOut(duration: 0.2), value: chatDrawerOpen)
        .task(id: meetingID) {
            chatHistory = []
            chatDrawerOpen = false
            await reload()
            // Keep the open meeting fresh while it is being processed, so a
            // stage change or failure shows without a click.
            while !Task.isCancelled {
                try? await Task.sleep(for: .seconds(2))
                await reload(keepingDraft: true)
            }
        }
    }

    // MARK: - Header

    @ViewBuilder
    private func header(_ detail: MeetingDetail) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            HStack {
                if titleDraft != nil {
                    TextField("Meeting title", text: Binding(
                        get: { titleDraft ?? "" },
                        set: { titleDraft = $0 }))
                        .textFieldStyle(.roundedBorder)
                        .font(.title2)
                        .frame(maxWidth: 420)
                        .focused($titleFocused)
                        .onAppear { titleFocused = true }
                        .onSubmit { saveTitle() }
                        .onExitCommand { titleDraft = nil }
                        .onChange(of: titleFocused) { _, focused in
                            if !focused && titleDraft != nil { saveTitle() }
                        }
                } else {
                    Text(detail.title)
                        .font(.title2).bold()
                        .onTapGesture { titleDraft = detail.title }
                        .help("Click to rename this meeting")
                }
                Spacer()
                if detail.processing_status == "failed" {
                    Button("Retry from \(detail.failed_stage ?? "the failed stage")") {
                        Task {
                            try? await model.client.retry(meetingID)
                            await reload()
                            await model.refreshLibrary()
                        }
                    }
                }
                Button("Reveal in Finder") {
                    model.revealInFinder(path: detail.reveal_path)
                }
            }
            if detail.processing_status == "failed" {
                Text(detail.last_error ?? "Processing failed.")
                    .font(.caption)
                    .foregroundStyle(.red)
                    .frame(maxWidth: .infinity, alignment: .trailing)
            }
            FolderBar(meetingID: meetingID, currentFolder: detail.folder) {
                await reload(keepingDraft: true)
                await model.refreshLibrary()
            }
        }
        .padding()
    }

    // MARK: - Tabs

    @ViewBuilder
    private func content(_ detail: MeetingDetail) -> some View {
        switch tab {
        case "Transcript":
            MarkdownPane(text: detail.transcript ?? "No transcript yet. It appears when processing reaches that stage.")
        case "Notes":
            VStack(alignment: .leading) {
                TextEditor(text: $notesDraft)
                    .font(contentFont)
                    .focused($notesFocused)
                    .onPasteCommand(of: [UTType.image]) { _ in
                        pasteImageFromPasteboard()
                    }
                    .onChange(of: notesFocused) { _, focused in
                        if !focused { saveNotes() }
                    }
                Text("Notes save on their own and feed into the summary; they are "
                     + "never rewritten. Paste screenshots straight in; they are "
                     + "stored with the meeting.")
                    .font(.caption).foregroundStyle(.secondary)
            }
            .padding()
            .onDisappear { saveNotes() }
        case "Speakers":
            SpeakersTab(meetingID: meetingID, attendees: detail.attendees.map(\.name)) {
                await reload(keepingDraft: true)
            }
        default:
            summaryTab(detail)
        }
    }

    @ViewBuilder
    private func summaryTab(_ detail: MeetingDetail) -> some View {
        if detail.summary == nil {
            MarkdownPane(text: detail.summary_status == "pending"
                ? "The summary is pending. It is written when LM Studio is reachable with a model loaded."
                : "No summary yet.")
        } else {
            VStack(alignment: .leading) {
                TextEditor(text: $summaryDraft)
                    .font(contentFont)
                    .focused($summaryFocused)
                    .onChange(of: summaryFocused) { _, focused in
                        if !focused { saveSummary() }
                    }
                Text("Your edits save on their own and are kept when speakers are "
                     + "renamed. Retry regenerates the summary from scratch.")
                    .font(.caption).foregroundStyle(.secondary)
            }
            .padding()
            .onDisappear { saveSummary() }
        }
    }

    // MARK: - Chat

    private var chatInputBar: some View {
        HStack {
            TextField("Ask about this meeting…", text: $chatQuestion)
                .textFieldStyle(.roundedBorder)
                .onSubmit { ask() }
            if chatBusy { ProgressView().controlSize(.small) }
            if !chatHistory.isEmpty && !chatDrawerOpen {
                Button("Show conversation") { chatDrawerOpen = true }
            }
        }
        .padding(10)
    }

    private func ask() {
        let question = chatQuestion.trimmingCharacters(in: .whitespaces)
        guard !question.isEmpty, !chatBusy else { return }
        chatQuestion = ""
        chatDrawerOpen = true
        chatBusy = true
        Task {
            defer { chatBusy = false }
            do {
                let answer = try await model.client.chat(
                    meetingID, question: question, history: chatHistory)
                chatHistory.append((question, answer))
            } catch {
                chatHistory.append((question, "The model could not answer: \(error.localizedDescription)"))
            }
        }
    }

    // MARK: - Saving

    private func saveTitle() {
        let title = (titleDraft ?? "").trimmingCharacters(in: .whitespaces)
        titleDraft = nil
        guard !title.isEmpty, title != detail?.title else { return }
        Task {
            try? await model.client.renameMeeting(meetingID, title: title)
            await reload(keepingDraft: true)
            await model.refreshLibrary()
        }
    }

    private func saveNotes() {
        let text = notesDraft
        guard text != lastSavedNotes else { return }
        lastSavedNotes = text
        Task { try? await model.client.saveNotes(meetingID, text: text) }
    }

    private func saveSummary() {
        let text = summaryDraft
        guard detail?.summary != nil, text != lastSavedSummary, !text.isEmpty else { return }
        lastSavedSummary = text
        Task { try? await model.client.saveSummary(meetingID, body: text) }
    }

    private func reload(keepingDraft: Bool = false) async {
        guard let fresh = try? await model.client.meeting(meetingID) else { return }
        detail = fresh
        if !keepingDraft || notesDraft.isEmpty {
            notesDraft = fresh.notes
            lastSavedNotes = fresh.notes
        }
        let freshSummary = summaryBody(fresh)
        if !keepingDraft || summaryDraft.isEmpty || summaryDraft == lastSavedSummary {
            // Adopt outside changes (a rename patch, a regeneration) unless
            // the user has unsaved edits in the editor right now.
            if freshSummary != lastSavedSummary {
                summaryDraft = freshSummary
                lastSavedSummary = freshSummary
            } else if !keepingDraft {
                summaryDraft = freshSummary
            }
        }
    }

    private func summaryBody(_ detail: MeetingDetail) -> String {
        guard let summary = detail.summary else { return "" }
        // meeting.md carries front matter; the editor holds only the body.
        if summary.hasPrefix("---\n"),
           let range = summary.range(of: "\n---\n", range: summary.index(summary.startIndex, offsetBy: 4)..<summary.endIndex) {
            return String(summary[range.upperBound...]).trimmingCharacters(in: .whitespacesAndNewlines)
        }
        return summary
    }

    private func pasteImageFromPasteboard() {
        let pasteboard = NSPasteboard.general
        let png = pasteboard.data(forType: .png)
            ?? pasteboard.data(forType: .tiff).flatMap {
                NSBitmapImageRep(data: $0)?.representation(using: .png, properties: [:])
            }
        guard let png else { return }
        Task {
            // Typed text first, so the backend appends the image link after it.
            try? await model.client.saveNotes(meetingID, text: notesDraft)
            _ = try? await model.client.pasteImage(meetingID, data: png)
            if let fresh = try? await model.client.meeting(meetingID) {
                detail = fresh
                notesDraft = fresh.notes
                lastSavedNotes = fresh.notes
            }
        }
    }
}

// MARK: - The conversation drawer

struct ChatDrawer: View {
    let history: [(question: String, answer: String)]
    @Binding var question: String
    let busy: Bool
    let onAsk: () -> Void
    let onClose: () -> Void

    var body: some View {
        VStack(spacing: 0) {
            HStack {
                Text("Conversation").font(.headline)
                Spacer()
                Button {
                    onClose()
                } label: {
                    Image(systemName: "chevron.down")
                }
                .buttonStyle(.borderless)
                .help("Close the conversation")
            }
            .padding(12)
            Divider()
            ScrollViewReader { proxy in
                ScrollView {
                    VStack(alignment: .leading, spacing: 14) {
                        ForEach(history.indices, id: \.self) { index in
                            VStack(alignment: .leading, spacing: 4) {
                                Text(history[index].question).bold()
                                Text(LocalizedStringKey(history[index].answer))
                                    .textSelection(.enabled)
                            }
                            .id(index)
                        }
                        if busy { ProgressView().controlSize(.small) }
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding(12)
                }
                .onChange(of: history.count) { _, count in
                    withAnimation { proxy.scrollTo(max(0, count - 1), anchor: .bottom) }
                }
            }
            Divider()
            HStack {
                TextField("Follow up…", text: $question)
                    .textFieldStyle(.roundedBorder)
                    .onSubmit { onAsk() }
                if busy { ProgressView().controlSize(.small) }
            }
            .padding(10)
        }
        .background(.regularMaterial)
        .clipShape(UnevenRoundedRectangle(topLeadingRadius: 10, topTrailingRadius: 10))
        .shadow(radius: 8)
    }
}

struct MarkdownPane: View {
    let text: String

    var body: some View {
        ScrollView {
            Text(LocalizedStringKey(text))
                .frame(maxWidth: .infinity, alignment: .leading)
                .textSelection(.enabled)
                .padding()
        }
    }
}
